# @format

backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Manage Content"
    name: "content"
    editor:
      preview: false
    files:
      - label: "Photo Gallery"
        name: "photo_gallery"
        file: "src/_data/gallery.yaml"
        fields:
          - label: "Photos"
            name: photos
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - {
                  label: "Image",
                  name: "image",
                  widget: "image",
                  allow_multiple: false,
                  hint: "Choose the image you would like to add to the photo gallery.",
                }
              - {
                  label: "Orientation",
                  name: "orientation",
                  widget: select,
                  multiple: false,
                  create: false,
                  options: ["Landscape", "Portrait", "Square"],
                  hint: "Select the orientation of the image being uploaded. If you're not sure, choose Landscape",
                }
              - {
                  label: "Caption",
                  name: "caption",
                  widget: "string",
                  required: false,
                  hint: "Add a caption to the image. When the image is expanded, the caption will be displayed beneath it. Not required.",
                }
              - {
                  label: "Use Caption as Alt Text",
                  name: "caption_as_alt",
                  widget: "boolean",
                  hint: "Set to true to reuse the Caption as the Alt Text too. Saves typing.",
                  default: true,
                }
              - {
                  label: "Alt Text",
                  name: "alt",
                  widget: "string",
                  required: false,
                  hint: "Add an 'alt' attribute description to the image on the page. Useful for screen readers and SEO. Recommended, but not required.",
                }
      - label: "Site Info"
        name: "info"
        file: "src/_data/info.yaml"
        create: false
        editor:
          preview: false
        fields:
          - { label: "Company Name", name: "name", widget: "string" }
          - { label: "Owner", name: "owner", widget: "string" }
          - { label: "Phone Number", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
